name: Python CI/CD

on: 
  push:
    branches:
      - main # mainブランチへのプッシュ時に実行
      - dev # devブランチへのプッシュ時にも実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # 使用するPythonのバージョン

    # - name: Verify Python and Pip before install
    #   run: |
    #     python --version
    #     pip --version
    #     pip list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    # - name: Verify installed packages after install
    #   run: pip list

    - name: Run tests
      run: python -m pytest 
